### ISSUE TITLE
Requirements 

### ISSUE THREAD

**Issue by Abiji-2020** [Abiji-2020/NexOrb#1]
# Disscussion about the requirements of the project workspace.

# Name of the project needed to be changed.

**Comment by Rageshwaran-HR** [comment]
I have a doubt about how is our project is going to be?
Are we making single website for all the facilities

**Comment by Abiji-2020** [comment]
> I have a doubt about how is our project is going to be? Are we making single website for all the facilities

For this we need to check on our requirement and feasibility of the development. And our core objective

**Comment by Abiji-2020** [comment]
@Rageshwaran-HR post the ideas here if you have any.

**Comment by Abiji-2020** [comment]
@lakshmikanthanC are you here ?

**Comment by Rageshwaran-HR** [comment]
I think some of the common things are
Chat with team, common discussion area
Kaban, calendar are some common things

**Comment by Rageshwaran-HR** [comment]
we can keep the task page 
Where the leader can assign task

**Comment by Rageshwaran-HR** [comment]
And as u said an common task page like open source problems listed
With leaderboard page

**Comment by Rageshwaran-HR** [comment]
Any thing u have

**Comment by Rageshwaran-HR** [comment]
And a project page where they can see how much task have been completed and what stage is the project. It can have downloaded option for the generated report
Which can be easily submitted.

**Comment by Rageshwaran-HR** [comment]
And if possible even we can make a feature same like slack or discord

**Comment by Abiji-2020** [comment]
I thought of adding a issue page with priority to have and linked them to the task board. so that they can easily know the stage at where the development are and how can we cope up and it will be helpful in estimating the deadline of the project

**Comment by Abiji-2020** [comment]
> And if possible even we can make a feature same like slack or discord

In mini project it is not feasible

**Comment by Rageshwaran-HR** [comment]
Mm we can

**Comment by Abiji-2020** [comment]
> I think some of the common things are Chat with team, common discussion area `Kaban`, calendar are some common things

what is kaban ???

**Comment by Abiji-2020** [comment]
> Mm we can

we can try for full project but it is not in our inital mini-project

**Comment by Rageshwaran-HR** [comment]
If we can spend atleast an 7hrs a week 
We can complete it before this sem

**Comment by Rageshwaran-HR** [comment]
That's why I have an idea, why not to create like zoho

**Comment by Rageshwaran-HR** [comment]
Like separate feature inseprate website

**Comment by Abiji-2020** [comment]
> If we can spend atleast an 7hrs a week We can complete it before this sem

it is not feasilble to work 7hours a week. and to debug errors and also integrate

**Comment by Abiji-2020** [comment]
> Like separate feature inseprate website

list the features

**Comment by Rageshwaran-HR** [comment]
So we can share this between sems and take it to our final project too

**Comment by Abiji-2020** [comment]
> Like separate feature inseprate website

more like seperate product for each work and create a complete suite like zoho ??

**Comment by Abiji-2020** [comment]
> So we can share this between sems and take it to our final project too

yes it will be the second stage development

**Comment by LakshmikanthanC** [comment]
i have idea about logo for the website 
like: A hand typing in keyboard  ok va

**Comment by Abiji-2020** [comment]
> i have idea about logo for the website like: A hand typing in keyboard ok va

reasoning and initally lets discuss more about the list of features that are going to be added

**Comment by Rageshwaran-HR** [comment]
*discord clone for channels and grp discussion in semi formal reson
*Kaban Callender and task scheduler as separate to manage the tasks
*Project tracker to know how far they are in their plan
*The common opensource website with leaderboard 
*Our own white board and documents manager

**Comment by Rageshwaran-HR** [comment]
Like Google docs

**Comment by Rageshwaran-HR** [comment]
*open courses website for the people to learn and track them

**Comment by Abiji-2020** [comment]
> - discord clone for channels and grp discussion in semi formal reson 

oh okay, this can be discussed more in the following.
  
> - Kaban Callender and task scheduler as separate to manage the tasks 

seemes good and can start desinging ig.


> - Project tracker to know how far they are in their plan 

more like adding milestones and having them completed or using the percentage or how we are going to track it or any other measures ??

> - The common opensource website with leaderboard 

explanation for this ??


> - Our own white board and documents manager

reasoning>

**Comment by Abiji-2020** [comment]
> *open courses website for the people to learn and track them

too much for now, not a core functionality

**Comment by LakshmikanthanC** [comment]
in the workplace we can also integrate ai also like chatbot.They can use in this workspace itself

**Comment by Abiji-2020** [comment]
> in the workplace we can also integrate ai also like chatbot.They can use in this workspace itself

wait wait, we can add it AI, is not a hard task to do, if we are using any api key with top layer as the data of ours. and that is pretty much not needed initially.

**Comment by Rageshwaran-HR** [comment]
S i to thought the same that's why gave it separate

**Comment by Rageshwaran-HR** [comment]
S ai is best idea

**Comment by Abiji-2020** [comment]
> S i to thought the same that's why gave it separate

for what you are replying ??

**Comment by Abiji-2020** [comment]
> S ai is best idea

it is not needed initially 🥲

**Comment by Rageshwaran-HR** [comment]
Mm that's great 👍

**Comment by Abiji-2020** [comment]
![image](https://github.com/user-attachments/assets/67aac0ab-1a25-48b3-85bf-11255a35df7a)
use the 3 dots to do quote reply so that we can know for which you are saying what.

**Comment by Rageshwaran-HR** [comment]
more like adding milestones and having them completed or using the percentage or how we are going to track it or any other measures ?

Like based on the task assigned for each member and how much are eventually completed based on the plan
So they can know if team is on track 
S like an management site and even it's great for customer to see it its use full

**Comment by Abiji-2020** [comment]
or try to think and decide is AI a core feature ? and if  it is how can we build an AI model ? for a workspace what is lacking and what can be added

**Comment by Abiji-2020** [comment]
>> more like adding milestones and having them completed or using the percentage or how we are going to track it or any other measures ?
> 
> Like based on the task assigned for each member and how much are eventually completed based on the plan So they can know if team is on track S like an management site and even it's great for customer to see it its use full

so how can we keep a track of the percentage done? It will be more tiresome to add those all individually

**Comment by LakshmikanthanC** [comment]
user login/authentication, 
access to shared documents and files, project management tools,
team communication channels,
calendars, 
task lists, 
document collaboration features, 
file sharing option,
 and potentially a personalized dashboard to view relevant information 
the basic common tasks in WorkSpace

**Comment by Rageshwaran-HR** [comment]
explanation for this ??
One u said this morning

**Comment by Abiji-2020** [comment]
> user login/authentication, access to shared documents and files, project management tools, team communication channels, calendars, task lists, document collaboration features, file sharing option, and potentially a personalized dashboard to view relevant information  the basic common tasks in WorkSpace

chatgpt ahh????

**Comment by Rageshwaran-HR** [comment]
U have any other doubt in the above idea?

**Comment by Abiji-2020** [comment]
> explanation for this ?? One u said this morning

hmm i guess we can disscuss more on a discord call

**Comment by Abiji-2020** [comment]
> U have any other doubt in the above idea?

use bulletins to list the exact features we can refactor them, since there are many talks and confusions going on

**Comment by LakshmikanthanC** [comment]
frontend for react da

**Comment by Abiji-2020** [comment]
> frontend for react da

wait still now requirements are not fixed.

**Comment by Rageshwaran-HR** [comment]
> > explanation for this ?? One u said this morning
> 
> hmm i guess we can disscuss more on a discord call

Mm ok

**Comment by Rageshwaran-HR** [comment]
> frontend for react da

Nextjs ?

**Comment by Abiji-2020** [comment]
https://discord.gg/hTHTY77u we can discuss further here

**Comment by Abiji-2020** [comment]
Requirements Initial 
•	Core Features:
o	User authentication (login, signup).
o	Group channels with topic-based chats.
o	Common chat for all users.
o	Personal chat (one-on-one messaging).
•	Additional Features:
o	Notifications for new messages.
o	Typing indicators.
o	Message reactions (like emojis).
o	File sharing (images, videos, documents).
